export const COUNTER_CHANGE = 'COUNTER_CHANGE'
export const GET_USERS_FETCH = "GET_USERS_FETCH"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_PRODUCTS_FETCH = "GET_PRODUCTS_FETCH"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const CHANGE_PRODUCT_STATUS = "CHANGE_PRODUCT_STATUS"